language: node_js
addons:
  firefox: "31.0"
node_js:
  - "8.4.0"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run-script symlink-plugin-to-ckeditor
  - npm install
env:
  - NPM_CMD=test
  - NPM_CMD=lint
script:
  - "npm run-script $NPM_CMD"
