language: node_js
dist: precise
cache: yarn
sudo: required
addons:
  firefox: "31.0"
  phantomjs: "1.9.8"
node_js:
  - "4.8.0"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run-script symlink-plugin-to-ckeditor
  - npm install
env:
  - NPM_CMD=test
  - NPM_CMD=lint
script:
  - "npm run-script $NPM_CMD"
